### ISSUE TITLE
Alt-text quotes not escaped

### ISSUE THREAD

**Issue by david-morris** [slidewiki/slidewiki-platform#1162]
If you look at the image metadata in the store on [this presentation](https://slidewiki.org/deck/127208/alttext-tests), you'll see that US-style quote marks (") were saved in the underlying database, instead of html & code `&quot`.  That was achieved by entering the " symbol into the "caption" form while creating the figure.  This means that alt text cannot contain quotes entered as such.

**Comment by david-morris** [comment]
An example of one response:

    curl -X GET --header 'Accept: application/json' 'https://fileservice.slidewiki.org/metadata/8c7045ea5b353cfa36d3b0551c179bcfd6e7351493e005db1a0e30f21b803a10.png'

> {
 ...
>       "Artifacts":{
>          "filename":"/data/files/pictures/8c7045ea5b353cfa36d3b0551c179bcfd6e7351493e005db1a0e30f21b803a10.png",
>          "verbose":"true"
>       },
>       "Tainted":"False",
>       "Filesize":"44.1KB",
>       "Number_pixels":"1.638M",
>       "Pixels_per second":"54.61MB",
>       "User_time":"0.030u",
>       "Elapsed_time":"0:01.030",
>       "Version":"ImageMagick 6.8.9-9 Q16 x86_64 2018-10-03 http://www.imagemagick.org"
>    },
>    "thumbnailName":"8c7045ea5b353cfa36d3b0551c179bcfd6e7351493e005db1a0e30f21b803a10_thumbnail.png",
>    "title":"1280px-Cc.logo.circle.svg.png",
>    "altText":"test escapes \\ \\\\ \""
> }

**Comment by david-morris** [comment]
On the last slide, I've demonstrated that using `&quot` in the caption entry bar does result in quote symbols in the alt text.

**Comment by aoelen** [comment]
I've just created a PR that solves this issue. This PR makes it possible to use quotes in alt-texts of images. The saving is still the same (i.e. the text won't be escaped on save), but when the image is added to the slide, Jquery's attr function will be used. This ensures that the text is not inserted as HTML, but as plain text.

**Comment by bwulff** [comment]
Thanks for this fix!
Ideally this issue should be solved in the file service (or by platform) but in any case when the text is submitted. 
But we will use this fix for the time being!

**Comment by aoelen** [comment]
You're welcome! I actually prefer this approach instead of escaping the text on submit/save. Mainly because the text is left intact with this approach, so the original alt text is not altered. This has some benefits, e.g. when the text is being searched.

Platform should then ensure that the text is displayed correctly (using the correct APIs etc.)
