### ISSUE TITLE
Wrong headline structure (BITV 1.3.1a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1167]
Following sites have a wrong headline structure:

1. The Add-Deck-site (https://slidewiki.org/addDeck) doen´t have a consistent headline structure. The headings h1 and h2 are missing. "Füge eine Präsentation zu SlideWiki hinzu" should be h1.

![WrongHeadings](https://user-images.githubusercontent.com/48785136/57211089-51117700-6fdf-11e9-8091-b96199ae815c.PNG)

2. The My-Presentation-site (https://slidewiki.org/user/vivien.zschammer) doen´t have a consistent headline structure.

![grafik](https://user-images.githubusercontent.com/48785136/58858596-267f1080-86a8-11e9-84d6-2d9d568e6adc.png)

4.	https://slidewiki.org/deck/127411/test/slide/836159-1/
5.	https://slidewiki.org/deck/127411/_/slide/836159-1/836159-1:1/edit

![grafik](https://user-images.githubusercontent.com/48785136/58858637-43b3df00-86a8-11e9-81da-cb8441e2e63b.png)

**Comment by VivienDZB** [comment]
I just noticed that there´s still or again a wrong headline structure on the sites I mentioned under the points 2., 4. and 5.

**Comment by aoelen** [comment]
Thanks for letting me know. Point 2 is indeed not fixed, I'll have a look!

Point 4 & 5 are a bit harder to fix since the headings are coming from the slide content (and slide creators can decide themselves which headings to use there). So we have to think about how to fix this

**Comment by aoelen** [comment]
This has been fixed in the mentioned commits
