### ISSUE TITLE
Error messages not linked to form fields (BITV 3.3.1a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1169]
Page: https://slidewiki.org/addDeck

If nothing has been entered in the form fields marked with *, the error message appears after the form fields. The message is therefore difficult to find and it is also not linked to the form field.

If the message can only appear after the form, at least the attribute aria-describedby must be inserted on the respective form field and refer to the id attribute of the error message. Alternatively or additionally, it would be good to put the error message in front of the form.

**Comment by aoelen** [comment]
While working on the accessibility issues there are some points I want to address. 

**1. Semantic UI framework** 
This framework is from an accessibility perspective a bad choice. Especially for forms, it requires a lot of work to make them accessible. Right now, I have manually added some CSS classes but in the long term it is not desirable if a lot of custom CSS has to be added. Additionally Semantic UI is currently not actively maintained anymore. Currently Bootstrap is doing a better job with respect to accessibility. I think it makes sense for a gradual transition to Bootstrap.

**2. Complicated forms**
Some forms on the platform are complicated. For example, the add deck page (https://slidewiki.org/addDeck) contains a lot of form fields that are not required. I think it makes sense to have a good look at all forms on the platform, and try to find out if some form fields can be grouped into a hidden container. Then a button with "Show advanced options", can make the hidden form items appear. I think this lowers the barriers when creating a new deck. 

**3. Collect accessibility requirements in a wiki**
I think it would be a good idea to create a wiki page that lists all the accessibility guidelines of SlideWiki. I've created an example at: https://github.com/slidewiki/slidewiki-platform/wiki/Accessibility-guidelines-SlideWiki This makes it easier for developers to make their components accessible. This also provides some guidance on how certain components should be implemented and is helpful when referring to a certain rule. Maybe in the future some linter rules can be added based on this document. @VivienDZB you think this makes sense? 

@bwulff @kadevgraaf any thoughts on this?

**Comment by VivienDZB** [comment]
@aoelen Actually those accessibility guidelines already exit on the WCAG page...also with examples on how to make web pages accessible. But of course they are very extensive and mostly kept realtively general. So I think it would make sense to create this wiki page and collect the guidelines that are specific to SlideWiki and add examples that give further information on how to solve those issues.
