### ISSUE TITLE
Fix bugs and inconsistencies with dropdowns

### ISSUE THREAD

**Issue by aoelen** [slidewiki/slidewiki-platform#1186]
Currently in SlideWiki different types of dropdowns (or select) components are used. E.g. Semantic UI JQuery, Semantic UI React, native browser select and custom made dropdown elements. This results in inconsistent behavior of those components. Additionally, it is hard to maintain these different components (i.e. making them accessible etc.).

I'm trying to replace all dropdowns by the Semantic UI React component. This component automatically adds (most) aria-* attributes. I replace this at several pages now, but I need someone to test the accessibility thoroughly before I continue to replace this everywhere. In case some of these dropdowns are not accessible, I will fork Semantic UI React, and implement this myself (afterwards merge it back into Semantic UI React).

I started this work in the branch: `Consistent-dropdowns`. The following dropdowns have been replaced:

- Personal settings: User Interface Language (regular dropdown)
- Personal settings: Country (searchable dropdown)
- Deck settings: Choose deck theme (regular dropdown)
- Deck settings: Education Level (regular dropdown)
- Deck settings: Add users for edit rights (async searchable dropdown without selection)

@VivienDZB Do you have a local version of SlideWiki running? If so, can you check out the branch locally and test if the replaced dropdowns are fully compliant to the accessibility standards? Thanks!

**Comment by VivienDZB** [comment]
@aoelen I don´t have a local version. Why is this important for checking the dropdowns?

**Comment by aoelen** [comment]
Because before merging this would be nice to get some feedback on the changes. Currently I'm only testing the elements with the native VoiceOver screen reader in Mac OS.

**Comment by VivienDZB** [comment]
What exactly do you mean by local version? How do I get a local version? Mayve those are stupid questions, but I don´t really get it right now.

**Comment by aoelen** [comment]
Sorry I didn't really explain it. Currently @bwulff and me are working on releasing this code to the experimental part of SlideWiki (then you will be able to test it). I'll let you know when we are done.
