### ISSUE TITLE
SlideWiki responsive pages

### ISSUE THREAD

**Issue by aoelen** [slidewiki/slidewiki-platform#1187]
Work has been done already on making SlideWiki responsive. But some extra work is needed to ensure that all pages are responsive and rendered correctly. I think it makes sense to first list all pages/components that don't work well on small screens and afterwards fix them. 

Additionally, the mobile version should be tested with mobile screen readers (for example Talkback on Android and VoiceOver on iOS). 

This work is part of WP5 (T5.2) in the iOCW task description. 

@rezatavakoli is working on detecting issues w.r.t. responsiveness.

**Comment by rezatavakoli** [comment]
The responsiveness has been checked on both Chrome and Firefox with Galaxy Note 10 and the following items should be handled:

- [Sign-In page]
- Size of the textboxes
- Close-Button position

**Comment by aoelen** [comment]
Thank you for checking! 

After fixing the issues you found, a next step is to also check the usability for mobile devices. This is related to what you have done already. E.g. checking whether buttons are large enough, and see if there is sufficient margin between them.

Some reference material: https://developers.google.com/web/fundamentals/accessibility/accessible-styles#multi-device_responsive_design

According to this recommendation, the target size should be at least 48 device independent pixels (corresponds to around 9mm)
