### ISSUE TITLE
Screen reader captioning for search fields

### ISSUE THREAD

**Issue by bwulff** [slidewiki/slidewiki-platform#1190]
When using SlideWiki with JAWS, the two input fields for the search are read (captioned) as follows (when German is the browser language/UI langauge):

Chrome 76:
1. Nicht bezeichnet Eingabefeld
2. Willkommen bei SlideWiki Eingabefeld

Firefox 52:
1. Search Eingabefeld
2. Search for decks or people

So there are different captions read in different browsers, this should be consistent. 

Also note: The English version is more consistent. So the inconsistency in German is most likely rooted in the internationalization.

There is additional information available on how to this should be approached (get it from Ben)

**Comment by aoelen** [comment]
I just created PR #1196 to fix this problem. The implementation of the hidden heading was incorrect (the HTML hidden attribute was hiding the label from screenreaders). However, I do not have JAWS installed so would be nice if this can be tested by somebody else.

**Comment by VivienDZB** [comment]
Unfortunately I don´t have JAWS either, but I just tested it with NVDA and it´s fine. So I guess it should work with JAWS as well.
