### ISSUE TITLE
Keyboard shortcuts (BITV 2.1.4a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1234]
**Request:** If websites implement keyboard shortcuts via single keys (letters, numbers, punctuation marks or symbols), they can either be switched off or switched to a key combination with modifier keys.

**Issue:**
1. https://slidewiki.org/presentation/81127-1/overview-of-accessibility/811271/437649-3/?language=en-/slide-719796-3 
- Pressing the b, ü and m keys on the keyboard changes the website, which cannot be switched off or changed by the user.

**Comment by aoelen** [comment]
This issue is unfortunately also hard to fix (sorry again the story of dependency packages). I will mark this as won't fix. Some of the shortcuts are already disabled by removing the menu (e.g. 'm').
