### ISSUE TITLE
Change of context (WCAG 3.2.1)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1240]
**Request:** The intent of this criterion is to ensure that functionality is predictable as visitors navigate their way through a document. Any component that is able to trigger an event when it receives focus must not change the context.

**Issue:** 
1. https://slidewiki.org/deck/127411/_/slide/836159-2/836159-2:1/edit 
- Focusing the button "Open Slideshow in new tab" leads to a context change of the page, which should only happen by activating the button.

**Comment by aoelen** [comment]
If I understand it correctly, when you focus the button "Open Slideshow in new tab" with tabbing around, a new tab is opened (without hitting enter first). This this correct?

Because I wasn't able to reproduce this problem. For me, only the new tab is opened when I git enter / space.

**Comment by VivienDZB** [comment]
When focussing the button, there was a reload of the page which should not happen without activating it. But it seems like that this is fixed because it´s not happening anymore.
