### ISSUE TITLE
Upload button disabled

### ISSUE THREAD

**Issue by pierorex** [slidewiki/slidewiki-platform#749]
I'm trying to upload a new deck and after I select it from my files the upload button is disabled as shown below in the image, thus not allowing me to upload it.
I'm not sure if it's a bug or the expected behavior because of some permissions I don't have or something similar.

I'm running the platform locally and using all the services from the experimental server.
I'm at this commit: 1dcab754ddec2112c41dbac7ade27b3a254f2f29.
Using Google Chrome version 64.0.3282.119 (Official Build) (64-bit)
Ubuntu 17.10

![upload-button-not-working](https://user-images.githubusercontent.com/9373636/35810136-fb2616da-0a8a-11e8-9edf-9e85e9576297.png)

In the console I see this message when I select the file:
![console-file-output](https://user-images.githubusercontent.com/9373636/35810495-40fa34ce-0a8c-11e8-9135-8ce554208765.png)

**Comment by dpaun** [comment]
Hi, Piero. I've managed to recreate this by using a pptx file for which the system does not have access permissions (looking at files properties ->Permissions - Others). This is producing a 'File not found' error (also visible in the console). Could it be that this was also the problem when you were trying?

**Comment by pierorex** [comment]
Hi @dpaun.
I know there are read, write and execute permissions, not sure what you mean by "access permissions".
In my laptop, the file has permissions set as "-rw-rw-rw-" (Unix format).

**Comment by dpaun** [comment]
Hmm, then it should not be a problem (I meant read permission).
I'll check some more.

**Comment by Sole-Valero** [comment]
[powerpoint.pptx](https://github.com/slidewiki/slidewiki-platform/files/1699641/powerpoint.pptx)
We have just merged a new version of this component. Using it, I can upload without problems the same file than Piero tried. I did it using chrome from windows (Versión 63.0.3239.132 (Build oficial) (64 bits))

**Comment by pierorex** [comment]
Solved here 1fbb1fbd12f269b2d57f92e3574f69700efde468
